$("#button_a").click(function(){
	console.log(this.id);
	$.ajax({
		url:"http://127.0.0.1:8888/one-websit/asd.htm?haha=zmz;me=zhangmingzhi;age=24",
		type:'POST',
		data:{"me":"zhangmingzhi"},
		success:function(o){
			console.log(o);
			$("#content").html(o);
		}
	})
})